query AllLoyaltiesByDispensaryId( $dispensaryId: String!) {
  allLoyaltiesByDispensaryId(dispensaryId: $dispensaryId) {
    id
    dispensaryId
    name
    type
    applyDurationSet
    applyTo
    applyFrom
    pointWorth
    isActive
    isAdminPin
    color
    createdAt
    updatedAt   
  }
}