query AllOrdersByDispensaryIdAndDate( $dispensaryId: String!, $orderDate: String!) {
  allOrdersByDispensaryIdAndDate(dispensaryId: $dispensaryId, orderDate: $orderDate) {
      id           
      dispensaryId 
      userId       
      customerId   
      customer {
        name
        isMedical
      }
      description  
      orderType
      cost  
      cashAmount 
      otherAmount
      changeDue
      loyalty
      discount
      status       
      orderDate      
      createdAt    
      updatedAt    
  }
}