query AllPackagesByDispensaryId($dispensaryId: String!) {
  allPackagesByDispensaryId(dispensaryId: $dispensaryId) {
    packageStatus
    productId
    cost
    ContainsRemediatedProduct
    ExpirationDate
    FinishedDate
    InitialLabTestingState
    IsDonation
    IsDonationPersistent
    IsFinished
    IsOnHold
    IsOnRetailerDelivery
    IsOnTrip
    IsProcessValidationTestingSample
    IsProductionBatch
    IsTestingSample
    IsTradeSample
    IsTradeSamplePersistent
    ItemFromFacilityLicenseNumber
    ItemFromFacilityName
    LabTestResultExpirationDateTime
    LabTestingPerformedDate
    LabTestingRecordedDate
    LabTestingState
    LabTestingStateDate
    packageLabel
    LastModified
    LocationId
    LocationName
    LocationTypeName
    Note
    PackageForProductDestruction
    PackageType
    PackagedDate
    PatientLicenseNumber
    ProductRequiresRemediation
    ProductionBatchNumber
    Quantity
    ReceivedDateTime
    ReceivedFromFacilityLicenseNumber
    ReceivedFromFacilityName
    ReceivedFromManifestNumber
    RemediationDate
    RetailIdQrCount
    SellByDate
    SourceHarvestCount
    SourceHarvestNames
    SourcePackageCount
    SourcePackageIsDonation
    SourcePackageIsTradeSample
    SourcePackageLabels
    SourceProcessingJobCount
    SourceProductionBatchNumbers
    UnitOfMeasureAbbreviation
    UnitOfMeasureName
    UseByDate
    createdAt
    dispensaryId
    id
    itemAdministrationMethod
    itemAllergens
    itemApprovalStatus
    itemApprovalStatusDateTime
    itemDefaultLabTestingState
    itemDescription
    itemHasExpirationDate
    itemHasSellByDate
    itemHasUseByDate
    itemId
    itemIsExpirationDateRequired
    itemIsSellByDateRequired
    itemIsUseByDateRequired
    itemIsUsed
    itemItemBrandId
    itemItemBrandName
    itemLabTestBatchNames
    itemLabelImages
    itemLabelPhotoDescription
    itemName
    itemNumberOfDoses
    itemPackagingImages
    itemPackagingPhotoDescription
    itemProcessingJobCategoryName
    itemProductBrandName
    itemProductCategoryName
    itemProductCategoryType
    itemProductImages
    itemProductPDFDocuments
    itemProductPhotoDescription
    itemPublicIngredients
    itemQuantityType
    itemServingSize
    itemStrainId
    itemStrainName
    itemUnitOfMeasureName
    itemUnitQuantity
    itemUnitQuantityUnitOfMeasureName
    itemUnitVolume
    itemUnitVolumeUnitOfMeasureName
    itemUnitWeight
    itemUnitWeightUnitOfMeasureName
    packageId
    updatedAt
  }
}