query AppPrintSettingByDispensaryId( $dispensaryId: String!) {
  appPrintSettingByDispensaryId(dispensaryId: $dispensaryId) {
      dispensaryId
      autoPrintReceiptOnComplete
      autoPrintExitLabelsOnComplete
  }
}
