query DrawerInfoByDrawerId( $drawerId: String!) {
  drawerInfoByDrawerId(drawerId: $drawerId) {
    cashSales
    expectedCash
    incomingDrops
    otherSales
    changeDue
    outgoingDrops
    startingBalance
  }
}