query GetPackageRowsByItemSearch($searchQuery: String!, $dispensaryId: String!) {
  getPackageRowsByItemSearch(searchQuery: $searchQuery, dispensaryId: $dispensaryId) {
    id
    itemName
    itemProductCategoryName
    Quantity
    UnitOfMeasureAbbreviation
  }
}