query GetTinyMetrcQtyPackagesByDispensaryId($dispensaryId: String!, $pageNumber: Int!, $onePageRecords: Int!, $searchField: String!, $searchParam: String!, $sortField: String, $sortDirection: String) {
  getTinyMetrcQtyPackagesByDispensaryId(dispensaryId: $dispensaryId, pageNumber: $pageNumber, onePageRecords: $onePageRecords, searchField: $searchField, searchParam: $searchParam, sortField: $sortField, sortDirection: $sortDirection) {
    packages{
      packageId
      packageLabel
      assignPackage {
        productId
        product {
          name
          productUnitOfMeasure
        }
        originalQty
        posQty
        cost
      }
      originalQty
      Quantity
      posQty
      id
      packageStatus
      createdAt
    },
    totalCount
  }
}