query MetrcAdjustmentReasonsByDispensaryId( $dispensaryId: String!) {
  metrcAdjustmentReasonsByDispensaryId(dispensaryId: $dispensaryId) {
    Name
    RequiresImmatureWasteWeight
    RequiresMatureWasteWeight
    RequiresNote
    RequiresWasteWeight
  }
}