query PackagesByDeliveryId($deliveryId: Int!) {
  packagesByDeliveryId(deliveryId: $deliveryId) {
    ReceivedQuantity
    ReceivedUnitOfMeasureName
    ShipmentPackageState
    ShippedQuantity
    id
    dispensaryId
    deliveryId
    packageId
    packageLabel
    ShippedUnitOfMeasureName
    createdAt
    updatedAt
    package {
      assignPackage {
        posQty
        userId
        productId
        product {
          name
          sku
          upc
          price
          productUnitOfMeasure
          unitWeight
          netWeight
          isConnectedWithPackage
          createdAt  
          updatedAt
        }
        packageLabel
        originalQty
        posQty
        cost
        createdAt
        updatedAt
      }
      TestResult {
        packageId
        testComment
        testPassed
        testPerformedDate
        testResultLevel
        testTypeName
        sourcePackageLabel
        labTestResultId
        labTestResultDocumentFileId
        labFacilityLicenseNumber
        createdAt
        updatedAt
      }
      id
      dispensaryId
      packageId
      productId
      packageStatus
      packageLabel
      cost
      originalQty
      Quantity
      isConnectedWithProduct
      PackageType
      SourceHarvestCount
      SourcePackageCount
      SourceProcessingJobCount
      SourceHarvestNames
      SourcePackageLabels
      LocationId
      LocationName
      LocationTypeName
      UnitOfMeasureName
      UnitOfMeasureAbbreviation
      ItemFromFacilityLicenseNumber
      ItemFromFacilityName
      Note
      PackagedDate
      InitialLabTestingState
      LabTestingState
      LabTestingStateDate
      LabTestingPerformedDate
      LabTestResultExpirationDateTime
      LabTestingRecordedDate
      IsProductionBatch
      ProductionBatchNumber
      SourceProductionBatchNumbers
      SourcePackageIsTradeSample
      ReceivedDateTime
      ReceivedFromManifestNumber
      ReceivedFromFacilityLicenseNumber
      ReceivedFromFacilityName
      IsOnHold
      PackageForProductDestruction
      LastModified
      itemId
      itemName
      itemProductCategoryName
      itemProductCategoryType
      itemQuantityType
      itemDefaultLabTestingState
      itemUnitOfMeasureName
      itemUnitWeight
      itemUnitWeightUnitOfMeasureName
      itemPublicIngredients
      itemStrainId
      itemStrainName
      itemDescription
      itemIsUsed
      itemProcessingJobCategoryName
      itemProductBrandName
      createdAt
      updatedAt
    }
  }
}