query Package($id: String!) {
    package(id: $id) {
      id
      dispensaryId
      packageId
      assignPackage {
        product {
          id
          name
          price
          itemCategory {
            name
          }
          supplier {
            id
            name
          }
        }
        cost
        originalQty
        posQty
      }
      delivery {
        deliveryId
        transfer {
          id
          transferId
          transferType
          ReceivedDateTime
          PackageCount
        }
      }
      OrderItem {
        orderId
        order {
          metrcId
          orderDate
          status
        }
        quantity
        cost
        price
      }
      TestResult {
        packageId
        testComment
        testPassed
        testPerformedDate
        testResultLevel
        testTypeName
        sourcePackageLabel
        labTestResultId
        labTestResultDocumentFileId
        labFacilityLicenseNumber
        createdAt
        updatedAt
      }
      packageStatus
      packageLabel
      cost
      originalQty
      Quantity
      isConnectedWithProduct
      PackageType
      SourceHarvestCount
      SourcePackageCount
      SourceProcessingJobCount
      SourceHarvestNames
      SourcePackageLabels
      LocationId
      LocationName
      LocationTypeName
      UnitOfMeasureName
      UnitOfMeasureAbbreviation
      ItemFromFacilityLicenseNumber
      ItemFromFacilityName
      Note
      PackagedDate
      InitialLabTestingState
      LabTestingState
      LabTestingStateDate
      LabTestingPerformedDate
      LabTestResultExpirationDateTime
      LabTestingRecordedDate
      IsProductionBatch
      ProductionBatchNumber
      SourceProductionBatchNumbers
      SourcePackageIsTradeSample
      ReceivedDateTime
      ReceivedFromManifestNumber
      ReceivedFromFacilityLicenseNumber
      ReceivedFromFacilityName
      IsOnHold
      IsFinished
      FinishedDate
      PackageForProductDestruction
      LastModified
      itemId
      itemName
      itemProductCategoryName
      itemProductCategoryType
      itemQuantityType
      itemDefaultLabTestingState
      itemUnitOfMeasureName
      itemUnitWeight
      itemUnitWeightUnitOfMeasureName
      itemPublicIngredients
      itemStrainId
      itemStrainName
      itemDescription
      itemIsUsed
      itemProcessingJobCategoryName
      itemProductBrandName
      createdAt
      updatedAt
    }
}